	/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import entity.NhanVien;
import entity.TaiKhoan;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;




/**
 *
 * @author dell
 */
public class GiaoDienNhanVien extends javax.swing.JFrame {
    private JPanel childPanel;
    
    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienNhanVien(NhanVien nv, TaiKhoan taik) {
    	this.nhanvien = nv;
    	this.taikhoan = taik;
    	IconFontSwing.register(FontAwesome.getIconFont());
		ImageIcon logoApp = (ImageIcon) IconFontSwing.buildIcon(FontAwesome.SMILE_O, 50, new Color(164, 44,167));
		setIconImage(logoApp.getImage());
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//		setResizable(false);
//		setTitle("QUẢN LÝ KARAOKE NICE");
		
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public static JPanel getFrame() {
			return pnlChinh;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
 
    private void initComponents() {

        pnlChinh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mnuChucNang = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JMenuItem();
        mnuDanhMuc = new javax.swing.JMenu();
        mniDMChucVu = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniDMTaiKhoan = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        mniDMKhachHang = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        mniDMPhong = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mniDMLoaiPhong = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        mniDMDichVu = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        mniDMLoaiDichVu = new javax.swing.JMenuItem();
        mnuXuLy = new javax.swing.JMenu();
        mniXLLapPhieuDP = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniXLLapHoaDon = new javax.swing.JMenuItem();
        mnuTraCuu = new javax.swing.JMenu();
        mniTCKhachHang = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniTCPhong = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniTCDichVu = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        mniTCHoaDon = new javax.swing.JMenuItem();;
        mnuBaoCao = new javax.swing.JMenu();
        mniBaoCao = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        mniTaiKhoan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlChinh.setLayout(new java.awt.BorderLayout());

		JLabel lblBackground = new JLabel();
		ImageIcon bg = new ImageIcon("icon/anhnen2.jpg");
		Image i = bg.getImage().getScaledInstance(1920, 965, DO_NOTHING_ON_CLOSE);
		ImageIcon b = new ImageIcon(i);
		lblBackground.setIcon(b);
		lblBackground.setLayout(new FlowLayout());
		JLabel lblTitle = new JLabel("Chương Trình Quản Lý Quán Karaoke");
		lblTitle.setFont(new Font("Serif", Font.BOLD, 80));
		lblTitle.setForeground(Color.white);
		lblBackground.add(lblTitle);
		pnlChinh.add(lblBackground);

        mnuHeThong.setIcon(new javax.swing.ImageIcon("icon/HT-icon.png")); // NOI18N
        mnuHeThong.setText("Hệ Thống");
        mnuHeThong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuHeThong.setPreferredSize(new java.awt.Dimension(165, 53));

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon("icon/DX_icon.png")); // NOI18N
        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThoat.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniThoat.setIcon(new javax.swing.ImageIcon("icon/TH_icon.png")); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);
        mnuHeThong.add(jSeparator3);

        mniTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniTaiKhoan.setIcon(new javax.swing.ImageIcon("icon/people_icon.png"));
        mniTaiKhoan.setText("Tài Khoản Của Tôi");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniTaiKhoan);
        
        mnuChucNang.add(mnuHeThong);

        mnuDanhMuc.setIcon(new javax.swing.ImageIcon("icon/DM_icon.png")); // NOI18N
        mnuDanhMuc.setText("Danh Mục");
        mnuDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuDanhMuc.setPreferredSize(new java.awt.Dimension(168, 53));


        mniDMKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDMKhachHang.setIcon(new javax.swing.ImageIcon("icon/KH_icon.png")); // NOI18N
        mniDMKhachHang.setText("Khách Hàng");
        mniDMKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMKhachHangActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mniDMKhachHang);
        mnuDanhMuc.add(jSeparator13);

        mniDMPhong.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDMPhong.setIcon(new javax.swing.ImageIcon("icon/P_icon.png")); // NOI18N
        mniDMPhong.setText("Phòng");
        mniDMPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMPhongActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mniDMPhong);
        mnuDanhMuc.add(jSeparator14);

        mniDMLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDMLoaiPhong.setIcon(new javax.swing.ImageIcon("icon/LP_icon.png")); // NOI18N
        mniDMLoaiPhong.setText("Loại Phòng");
        mniDMLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMLoaiPhongActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mniDMLoaiPhong);
        mnuDanhMuc.add(jSeparator17);

        mniDMDichVu.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDMDichVu.setIcon(new javax.swing.ImageIcon("icon/DV_icon.png")); // NOI18N
        mniDMDichVu.setText("Dịch Vụ");
        mniDMDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMDichVuActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mniDMDichVu);
        mnuDanhMuc.add(jSeparator18);

        mniDMLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniDMLoaiDichVu.setIcon(new javax.swing.ImageIcon("icon/LDV_icon.png")); // NOI18N
        mniDMLoaiDichVu.setText("Loại Dịch Vụ");
        mniDMLoaiDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMLoaiDichVuActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mniDMLoaiDichVu);

        mnuChucNang.add(mnuDanhMuc);

        mnuXuLy.setIcon(new javax.swing.ImageIcon("icon/XL_icon.png")); // NOI18N
        mnuXuLy.setText("Xử Lý");
        mnuXuLy.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuXuLy.setPreferredSize(new java.awt.Dimension(119, 53));

        mniXLLapPhieuDP.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniXLLapPhieuDP.setIcon(new javax.swing.ImageIcon("icon/PDP_icon.png")); // NOI18N
        mniXLLapPhieuDP.setText("Lập Phiếu Đặt Phòng ");
        mniXLLapPhieuDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXLLapPhieuDPActionPerformed(evt);
            }
        });
        mnuXuLy.add(mniXLLapPhieuDP);
        mnuXuLy.add(jSeparator6);

        mniXLLapHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniXLLapHoaDon.setIcon(new javax.swing.ImageIcon("icon/HD_icon.png")); // NOI18N
        mniXLLapHoaDon.setText("Lập Hóa Đơn");
        mniXLLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXLLapHoaDonActionPerformed(evt);
            }
        });
        mnuXuLy.add(mniXLLapHoaDon);

        mnuChucNang.add(mnuXuLy);

        mnuTraCuu.setIcon(new javax.swing.ImageIcon("icon/TC_icon.png")); // NOI18N
        mnuTraCuu.setText("Tra Cứu");
        mnuTraCuu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuTraCuu.setPreferredSize(new java.awt.Dimension(143, 53));

        mniTCKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniTCKhachHang.setIcon(new javax.swing.ImageIcon("icon/KH_icon.png")); // NOI18N
        mniTCKhachHang.setText("Khách Hàng");
        mniTCKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTCKhachHangActionPerformed(evt);
            }
        });
        mnuTraCuu.add(mniTCKhachHang);
        mnuTraCuu.add(jSeparator4);

        mniTCPhong.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniTCPhong.setIcon(new javax.swing.ImageIcon("icon/P_icon.png")); // NOI18N
        mniTCPhong.setText("Phòng");
        mniTCPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTCPhongActionPerformed(evt);
            }
        });
        mnuTraCuu.add(mniTCPhong);
        mnuTraCuu.add(jSeparator5);

        mniTCDichVu.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniTCDichVu.setIcon(new javax.swing.ImageIcon("icon/DV_icon.png")); // NOI18N
        mniTCDichVu.setText("Dịch Vụ");
        mniTCDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTCDichVuActionPerformed(evt);
            }
        });
        mnuTraCuu.add(mniTCDichVu);
        mnuTraCuu.add(jSeparator15);

        mniTCHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniTCHoaDon.setIcon(new javax.swing.ImageIcon("icon/HD_icon.png")); // NOI18N
        mniTCHoaDon.setText("Hóa Đơn");
        mniTCHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTCHoaDonActionPerformed(evt);
            }
        });
        mnuTraCuu.add(mniTCHoaDon);

        mnuChucNang.add(mnuTraCuu);

        mnuBaoCao.setIcon(new javax.swing.ImageIcon("icon/BC_icon.png")); // NOI18N
        mnuBaoCao.setText("Báo Cáo");
        mnuBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuBaoCao.setPreferredSize(new java.awt.Dimension(149, 53));

        mniBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniBaoCao.setIcon(new javax.swing.ImageIcon("icon/BC_icon.png")); // NOI18N
        mniBaoCao.setText("Báo Cáo");
        mniBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBaoCaoActionPerformed(evt);
            }
        });
        mnuBaoCao.add(mniBaoCao);

        mnuChucNang.add(mnuBaoCao);

        mnuTroGiup.setIcon(new javax.swing.ImageIcon("icon/TG_icon.png")); // NOI18N
        mnuTroGiup.setText("Trợ Giúp");
        mnuTroGiup.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuTroGiup.setPreferredSize(new java.awt.Dimension(152, 53));

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHuongDan.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mniHuongDan.setIcon(new javax.swing.ImageIcon("icon/HDSD_icon.png")); // NOI18N
        mniHuongDan.setText("Hướng Dẫn");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);

        mnuChucNang.add(mnuTroGiup);

        setJMenuBar(mnuChucNang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 1491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        DangNhap frmDN = new DangNhap();
		frmDN.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniDMKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMKhachHangActionPerformed
        childPanel = new JPanel_DMKhachHang();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniDMKhachHangActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        // TODO add your handling code here:
    	HDSD.openHDSD();
    }//GEN-LAST:event_mniHuongDanActionPerformed


    private void mniTCHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTCHoaDonActionPerformed
        childPanel = new JPanel_TCHoaDon();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniTCHoaDonActionPerformed


    private void mniDMPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMPhongActionPerformed
        childPanel = new JPanel_DMPhong();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniDMPhongActionPerformed

    private void mniDMLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMLoaiPhongActionPerformed
        childPanel = new JPanel_DMLoaiPhong();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniDMLoaiPhongActionPerformed

    private void mniDMDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMDichVuActionPerformed
        childPanel = new JPanel_DMDichVu();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniDMDichVuActionPerformed

    private void mniDMLoaiDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMLoaiDichVuActionPerformed
        childPanel = new JPanel_DMLoaiDichVu();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniDMLoaiDichVuActionPerformed

    private void mniXLLapPhieuDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXLLapPhieuDPActionPerformed
        childPanel = new JPanel_XLLapPhieuDP();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniXLLapPhieuDPActionPerformed

    private void mniXLLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXLLapHoaDonActionPerformed
        childPanel = new JPanel_XLLapHoaDon();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniXLLapHoaDonActionPerformed

    private void mniTCKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTCKhachHangActionPerformed
        childPanel = new JPanel_TCKhachHang();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniTCKhachHangActionPerformed

    private void mniTCPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTCPhongActionPerformed
        childPanel = new JPanel_TCPhong();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniTCPhongActionPerformed

    private void mniTCDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTCDichVuActionPerformed
        childPanel = new JPanel_TCDichVu();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniTCDichVuActionPerformed

    private void mniBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBaoCaoActionPerformed
        childPanel = new JPanel_BaoCao();
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniBaoCaoActionPerformed
    
    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
    	childPanel = new JPanel_TaiKhoanCuaToi(nhanvien, taikhoan);
        pnlChinh.removeAll();
        pnlChinh.add(childPanel);
        pnlChinh.validate();
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GiaoDienNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuItem mniBaoCao;
    private javax.swing.JMenuItem mniDMChucVu;
    private javax.swing.JMenuItem mniDMDichVu;
    private javax.swing.JMenuItem mniDMKhachHang;
    private javax.swing.JMenuItem mniDMLoaiDichVu;
    private javax.swing.JMenuItem mniDMLoaiPhong;
    private javax.swing.JMenuItem mniDMPhong;
    private javax.swing.JMenuItem mniDMTaiKhoan;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniTCDichVu;
    private javax.swing.JMenuItem mniTCHoaDon;
    private javax.swing.JMenuItem mniTCKhachHang;
    private javax.swing.JMenuItem mniTCPhong;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenuItem mniXLLapHoaDon;
    private javax.swing.JMenuItem mniXLLapPhieuDP;
    private javax.swing.JMenuItem mniTaiKhoan;
    private javax.swing.JMenu mnuBaoCao;
    private javax.swing.JMenuBar mnuChucNang;
    private javax.swing.JMenu mnuDanhMuc;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuTraCuu;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JMenu mnuXuLy;
    private static javax.swing.JPanel pnlChinh;
    private NhanVien nhanvien;
    private TaiKhoan taikhoan;
    private static final long serialVersionUID = 1L;
    // End of variables declaration//GEN-END:variables
}
