/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

import dao.CT_HoaDon_DAO;
import dao.HoaDon_DAO;
import entity.CT_HoaDon;
import entity.HoaDon;

/**
 *
 * @author dell
 */
public class JPanel_TKDTTheoNamNV extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTKDTTheoNgay
     */
    public JPanel_TKDTTheoNamNV() {
    	hoaDon_DAO = new HoaDon_DAO();
    	ct_HoaDon_DAO = new CT_HoaDon_DAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNam = new javax.swing.JLabel();
        lblTongHD = new javax.swing.JLabel();
        lblTongHD2 = new javax.swing.JLabel();
        lblTongDT = new javax.swing.JLabel();
        lblTongDT2 = new javax.swing.JLabel();
        ychNamTK = new com.toedter.calendar.JYearChooser();
        btnThongKe = new JButton();
        pnlBieuDo = new JPanel();

        ychNamTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        
        lblNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNam.setText("Thống Kê Doanh Thu Theo Năm: ");

        lblTongHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongHD.setText("Tổng Hóa Đơn:");

        lblTongHD2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongDT.setText("Tổng Doanh Thu Trong Năm:");

        lblTongDT2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnThongKe.setIcon(new javax.swing.ImageIcon("icon/TK_icon.png"));
        btnThongKe.setBackground(new Color(230, 125, 0));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        pnlBieuDo.setBackground(new Color(255,255,255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBieuDo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTongHD2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblTongDT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTongDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNam)
                                .addGap(18, 18, 18)
                                .addComponent(ychNamTK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThongKe,javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ychNamTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe,javax.swing.GroupLayout.DEFAULT_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTongHD2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTongDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnThongKeActionPerformed(ActionEvent evt) {
    	modelNV = (DefaultTableModel) JPanel_TKDoanhThu.getTable().getModel();
    	int row =JPanel_TKDoanhThu.getTable().getSelectedRow();
    	if(row<0) {
    		JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên bạn muốn thống kê");
    	}else {
    		pnlBieuDo.removeAll();
    		chartPanel = new ChartPanel(createChart());
    		chartPanel.setPreferredSize(new java.awt.Dimension(1180, 770));
    		pnlBieuDo.add(chartPanel);
    	}
	}

    private JFreeChart createChart() {
    	int nam = ychNamTK.getYear();
    	String s = String.valueOf(nam);
        barChart = ChartFactory.createBarChart(
        		"BIỂU ĐỒ DOANH THU KARAOKE NICE NĂM " +s,
                "Tháng", "Doanh thu (VNĐ)",
                createDataset(), PlotOrientation.VERTICAL, false,false, false);
        return barChart;
	}

	private CategoryDataset createDataset() {
		modelNV = (DefaultTableModel) JPanel_TKDoanhThu.getTable().getModel();
    	int row =JPanel_TKDoanhThu.getTable().getSelectedRow();
    	String maNV = modelNV.getValueAt(row, 0).toString();
		final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
		int nam =ychNamTK.getYear();
		int m =0;
		double tongDTNam=0;
    	for(int l=1;l<=12;l++) {
    		int k=0;
    		double tongDTT=0;
    		for(int j=1;j<=31;j++) {
    			ArrayList<HoaDon> dsHD = hoaDon_DAO.getHDTheoThangvaNV(l, nam, j, maNV);
    			int i = 0;
    			double tongDTN=0;
    			for(HoaDon hd : dsHD) {
    				List<CT_HoaDon> dsCTHD = ct_HoaDon_DAO.getAllCTHDTheoMa(hd.getMaHoaDon());
    				if(dsCTHD==null) {
    					double tongtien =0;
    					tongtien =tongtien + hd.getTienPhong();
    					i++;
    					tongDTN = tongDTN + tongtien;
    				}else {
    					double tongtien =0;
    					double tienDV = 0;
    					for(CT_HoaDon cthd : dsCTHD) {
    						tienDV = cthd.getSoLuong()*cthd.getGiaBan() + tienDV;
    					}
    					tongtien =tienDV + hd.getTienPhong();
    					i++;
    					tongDTN = tongDTN + tongtien;
    				}
    			}
    			tongDTT = tongDTT + tongDTN;
    	        k = k+i;
    			}
    		String thang = String.valueOf(l);
	        dataset.addValue(tongDTT, "VNĐ", thang);
    		m = m+k;
    		tongDTNam = tongDTNam + tongDTT;	
    	}	
    	DecimalFormat formatter = new DecimalFormat("###,###,###");
		lblTongHD2.setText(String.valueOf(m));
		lblTongDT2.setText(formatter.format(tongDTNam)+" VNĐ");
        return dataset;
	}

    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblTongDT;
    private javax.swing.JLabel lblTongDT2;
    private javax.swing.JLabel lblTongHD;
    private javax.swing.JLabel lblTongHD2;
    private com.toedter.calendar.JYearChooser ychNamTK;
    private JButton btnThongKe;
    private JPanel pnlBieuDo;
    private ChartPanel chartPanel;
    private static JFreeChart barChart;
    private HoaDon_DAO hoaDon_DAO;
    private CT_HoaDon_DAO ct_HoaDon_DAO;
    private DefaultTableModel modelNV;
}

