/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.LoaiDichVu_DAO;
import dao.LoaiPhong_DAO;
import entity.LoaiDichVu;
import entity.LoaiPhong;

/**
 *
 * @author dell
 */
public class JPanel_DMLoaiDichVu extends javax.swing.JPanel {
	private LoaiDichVu_DAO loaiDV_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form Panel1
     */
    public JPanel_DMLoaiDichVu() {
        initComponents();
        tblLoaiDichVu.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblLoaiDichVu.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		loaiDV_DAO = new LoaiDichVu_DAO();
		DocDuLieuDatabaseVaoTable();
		txtMaLoaiDV.setText(loaiDV_DAO.getMaLoaiDV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinLoaiDV = new javax.swing.JPanel();
        lblMaLoaiDV = new javax.swing.JLabel();
        txtMaLoaiDV = new javax.swing.JTextField();
        lblTenLoaiDV = new javax.swing.JLabel();
        txtTenLoaiDV = new javax.swing.JTextField();
        pnlSuKien = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        pnlDanhSachLoaiDV = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblLoaiDichVu = new javax.swing.JTable();

        pnlThongTinLoaiDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Loại Dịch Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlThongTinLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMaLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaLoaiDV.setText("Mã Loại:");

        txtMaLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaLoaiDV.setMinimumSize(new java.awt.Dimension(50, 35));

        lblTenLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenLoaiDV.setText("Tên Loại:");

        txtTenLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenLoaiDV.setMinimumSize(new java.awt.Dimension(50, 35));

        javax.swing.GroupLayout pnlThongTinLoaiDVLayout = new javax.swing.GroupLayout(pnlThongTinLoaiDV);
        pnlThongTinLoaiDV.setLayout(pnlThongTinLoaiDVLayout);
        pnlThongTinLoaiDVLayout.setHorizontalGroup(
            pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLoaiDVLayout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addGroup(pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lblMaLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtMaLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(629, Short.MAX_VALUE))
        );
        pnlThongTinLoaiDVLayout.setVerticalGroup(
            pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLoaiDVLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCapNhat.setBackground(new Color(0,191,255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon("icon/CN-icon.png")); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoa.setBackground(new Color(0,191,255));
        btnXoa.setIcon(new javax.swing.ImageIcon("icon/Xoa_icon.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnThem.setBackground(new Color(0,191,255));
        btnThem.setIcon(new javax.swing.ImageIcon("icon/Them_icon.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoaTrang.setBackground(new Color(0,191,255));
        btnXoaTrang.setIcon(new javax.swing.ImageIcon("icon/XT_icon.png")); // NOI18N
        btnXoaTrang.setText("Xóa Trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuKienLayout = new javax.swing.GroupLayout(pnlSuKien);
        pnlSuKien.setLayout(pnlSuKienLayout);
        pnlSuKienLayout.setHorizontalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        pnlSuKienLayout.setVerticalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnlDanhSachLoaiDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Loại Dịch Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlDanhSachLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblLoaiDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Loại", "Tên Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLoaiDichVu.setRowHeight(30);
        tblLoaiDichVu.getTableHeader().setBackground(new Color(255, 127, 0));
        tblLoaiDichVu.setShowHorizontalLines(true);
        tblLoaiDichVu.setShowVerticalLines(true);
        scr.setViewportView(tblLoaiDichVu);

        javax.swing.GroupLayout pnlDanhSachLoaiDVLayout = new javax.swing.GroupLayout(pnlDanhSachLoaiDV);
        pnlDanhSachLoaiDV.setLayout(pnlDanhSachLoaiDVLayout);
        pnlDanhSachLoaiDVLayout.setHorizontalGroup(
            pnlDanhSachLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhSachLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE))
        );
        pnlDanhSachLoaiDVLayout.setVerticalGroup(
            pnlDanhSachLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(pnlDanhSachLoaiDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDanhSachLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinLoaiDV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDanhSachLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
		tblLoaiDichVu.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = tblLoaiDichVu.getSelectedRow();
				txtMaLoaiDV.setText(model.getValueAt(row, 0).toString());
				txtTenLoaiDV.setText(model.getValueAt(row, 1).toString());
			}
		});
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		if (txtMaLoaiDV.getText().equals("") || txtTenLoaiDV.getText().equals("")) {
			JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl1);
		} else {
	        if(validData()) {
	            LoaiDichVu ldv = new LoaiDichVu(txtMaLoaiDV.getText(), txtTenLoaiDV.getText());
				if(loaiDV_DAO.getAllLoaiDichVu().contains(ldv)) {
					JLabel lbl2 = new JLabel("Không được thêm trùng mã loại dịch vụ");
					lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
					JOptionPane.showMessageDialog(this, lbl2);
				} else {
		            loaiDV_DAO.addLoaiDichVu(ldv);
		            DocDuLieuDatabaseVaoTable();
		            xoaRongTextfields();
				}
	        }
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblLoaiDichVu.getSelectedRow();
		if (row != -1) {
	    	if (txtMaLoaiDV.getText().equals("") || txtTenLoaiDV.getText().equals("")) {
				JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
				lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl1);
			} else {
		        if(validData()) {
			        LoaiDichVu ldv = new LoaiDichVu(txtMaLoaiDV.getText(), txtTenLoaiDV.getText());
			        loaiDV_DAO.updateLoaiDichVu(ldv);
			        DocDuLieuDatabaseVaoTable();
			        xoaRongTextfields();
		        }
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn loại dịch vụ cần cập nhật");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblLoaiDichVu.getSelectedRow();
		if (row != -1) {
			JLabel lbl1 = new JLabel("Bạn có chắc muốn xóa không?");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			int ask = JOptionPane.showConfirmDialog(this, lbl1, "Cảnh Báo!", JOptionPane.YES_NO_OPTION);
			if(ask == JOptionPane.YES_OPTION) {
		    	loaiDV_DAO.deleteLoaiDichVu(txtMaLoaiDV.getText());
		        DocDuLieuDatabaseVaoTable();
				xoaRongTextfields();
				JLabel lbl2 = new JLabel("Xóa thành công");
				lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl2);
				if(row < loaiDV_DAO.getAllLoaiDichVu().size() - 1) {
					selectedRow(row);
				} else if(loaiDV_DAO.getAllLoaiDichVu().size() > 0) {
					row = 0;
					selectedRow(row);
				}
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn loại dịch vụ cần xóa");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed
    
    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
    	xoaRongTextfields();
    }//GEN-LAST:event_btnCapNhatActionPerformed

	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<LoaiDichVu> list = loaiDV_DAO.getAllLoaiDichVu();
				for (LoaiDichVu ldv : list) {
					Object [] row = {ldv.getMaLoai(),ldv.getTenLoai()};
					model.addRow(row);
				}
	}
	private void xoaRongTextfields() {
		txtMaLoaiDV.setText(loaiDV_DAO.getMaLoaiDV());
		txtTenLoaiDV.setText("");
	}
	private void selectedRow(int row) {
		if(row != -1) {
			tblLoaiDichVu.setRowSelectionInterval(row, row);
			tblLoaiDichVu.scrollRectToVisible(tblLoaiDichVu.getCellRect(row, row, true));
		}
	}
	private boolean validData() {
		String maLDV = txtMaLoaiDV.getText().trim(); 

		if (!(maLDV.length() > 0 && maLDV.matches("LDV\\d{3}"))) {
			JLabel lbl3 = new JLabel("Error: Mã loại dịch vụ theo mẫu: LDV + Dãy gồm 3 chữ số");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
			txtMaLoaiDV.requestFocus();;
			return false;
		}
		return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel lblMaLoaiDV;
    private javax.swing.JLabel lblTenLoaiDV;
    private javax.swing.JPanel pnlDanhSachLoaiDV;
    private javax.swing.JPanel pnlSuKien;
    private javax.swing.JPanel pnlThongTinLoaiDV;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tblLoaiDichVu;
    private javax.swing.JTextField txtMaLoaiDV;
    private javax.swing.JTextField txtTenLoaiDV;
    // End of variables declaration//GEN-END:variables
}
