/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.LoaiPhong_DAO;
import entity.ChucVu;
import entity.LoaiPhong;

/**
 *
 * @author dell
 */
public class JPanel_DMLoaiPhong extends javax.swing.JPanel {
	private LoaiPhong_DAO loaiPhong_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form Panel1
     */
    public JPanel_DMLoaiPhong() {
        initComponents();
        tblLoaiP.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblLoaiP.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		loaiPhong_DAO = new LoaiPhong_DAO();
		DocDuLieuDatabaseVaoTable();
		txtMaLoaiP.setText(loaiPhong_DAO.getMaLoaiP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinLP = new javax.swing.JPanel();
        lblMaLoaiP = new javax.swing.JLabel();
        txtMaLoaiP = new javax.swing.JTextField();
        lblTenLoaiP = new javax.swing.JLabel();
        txtTenLoaiP = new javax.swing.JTextField();
        lblSoNguoiToiDa = new javax.swing.JLabel();
        txtSoNguoiToiDa = new javax.swing.JTextField();
        lblGiaP = new javax.swing.JLabel();
        txtGiaP = new javax.swing.JTextField();
        pnlSuKien = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        pnlDanhSachLoaiP = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblLoaiP = new javax.swing.JTable();

        pnlThongTinLP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Loại Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlThongTinLP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMaLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaLoaiP.setText("Mã Loại:");

        txtMaLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaLoaiP.setMinimumSize(new java.awt.Dimension(50, 35));


        lblTenLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenLoaiP.setText("Tên Loại:");

        txtTenLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenLoaiP.setMinimumSize(new java.awt.Dimension(50, 35));
        
        lblSoNguoiToiDa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoNguoiToiDa.setText("Số Người:");

        txtSoNguoiToiDa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoNguoiToiDa.setMinimumSize(new java.awt.Dimension(50, 35));

        lblGiaP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGiaP.setText("Giá Phòng:");

        txtGiaP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlThongTinKHLayout = new javax.swing.GroupLayout(pnlThongTinLP);
        pnlThongTinLP.setLayout(pnlThongTinKHLayout);
        pnlThongTinKHLayout.setHorizontalGroup(
            pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKHLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSoNguoiToiDa, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoNguoiToiDa, 0, 407, Short.MAX_VALUE)
                    .addComponent(txtMaLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGiaP, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(lblTenLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaP, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(txtTenLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(295, 295, 295))
        );
        pnlThongTinKHLayout.setVerticalGroup(
            pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinKHLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaLoaiP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLoaiP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenLoaiP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLoaiP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoNguoiToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoNguoiToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCapNhat.setBackground(new Color(0,191,255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon("icon/CN-icon.png")); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoa.setBackground(new Color(0,191,255));
        btnXoa.setIcon(new javax.swing.ImageIcon("icon/Xoa_icon.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnThem.setBackground(new Color(0,191,255));
        btnThem.setIcon(new javax.swing.ImageIcon("icon/Them_icon.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoaTrang.setBackground(new Color(0,191,255));
        btnXoaTrang.setIcon(new javax.swing.ImageIcon("icon/XT_icon.png")); // NOI18N
        btnXoaTrang.setText("Xóa Trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuKienLayout = new javax.swing.GroupLayout(pnlSuKien);
        pnlSuKien.setLayout(pnlSuKienLayout);
        pnlSuKienLayout.setHorizontalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        pnlSuKienLayout.setVerticalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnlDanhSachLoaiP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Loại Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlDanhSachLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblLoaiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblLoaiP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Loại", "Tên Loại", "Số Người Tối Đa", "Giá Phòng (VNĐ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLoaiP.setRowHeight(30);
        tblLoaiP.getTableHeader().setBackground(new Color(255, 127, 0));
        tblLoaiP.setShowHorizontalLines(true);
        tblLoaiP.setShowVerticalLines(true);
        scr.setViewportView(tblLoaiP);

        javax.swing.GroupLayout pnlDanhSachKHLayout = new javax.swing.GroupLayout(pnlDanhSachLoaiP);
        pnlDanhSachLoaiP.setLayout(pnlDanhSachKHLayout);
        pnlDanhSachKHLayout.setHorizontalGroup(
            pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE))
        );
        pnlDanhSachKHLayout.setVerticalGroup(
            pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(pnlDanhSachKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlThongTinLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDanhSachLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDanhSachLoaiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
		tblLoaiP.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = tblLoaiP.getSelectedRow();
				txtMaLoaiP.setText(model.getValueAt(row, 0).toString());
				txtTenLoaiP.setText(model.getValueAt(row, 1).toString());
				txtSoNguoiToiDa.setText(model.getValueAt(row, 2).toString());
				txtGiaP.setText(model.getValueAt(row, 3).toString());
			}
		});
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		if (txtMaLoaiP.getText().equals("") || txtTenLoaiP.getText().equals("") || txtGiaP.getText().equals("")) {
			JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl1);
		} else {
	        if(validData()) {
	            LoaiPhong lp = new LoaiPhong(txtMaLoaiP.getText(), txtTenLoaiP.getText(), Integer.parseInt(txtSoNguoiToiDa.getText()), Double.parseDouble(txtGiaP.getText()));
				if(loaiPhong_DAO.getAllLoaiPhong().contains(lp)) {
					JLabel lbl2 = new JLabel("Không được thêm trùng mã loại phòng");
					lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
					JOptionPane.showMessageDialog(this, lbl2);
				} else {
		            loaiPhong_DAO.addLoaiPhong(lp);
		            DocDuLieuDatabaseVaoTable();
		            xoaRongTextfields();
				}
	        }
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblLoaiP.getSelectedRow();
		if (row != -1) {
	    	if (txtMaLoaiP.getText().equals("") || txtTenLoaiP.getText().equals("") || txtGiaP.getText().equals("")) {
				JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
				lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl1);
			} else {
		        if(validData()) {
			        LoaiPhong lp = new LoaiPhong(txtMaLoaiP.getText(), txtTenLoaiP.getText(), Integer.parseInt(txtSoNguoiToiDa.getText()),  Double.parseDouble(txtGiaP.getText()));
			        loaiPhong_DAO.updateLoaiPhong(lp);
			        DocDuLieuDatabaseVaoTable();
			        xoaRongTextfields();
		        }
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn loại phòng cần cập nhật");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}

    }//GEN-LAST:event_btnCapNhatActionPerformed
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblLoaiP.getSelectedRow();
		if (row != -1) {
			JLabel lbl1 = new JLabel("Bạn có chắc muốn xóa không?");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			int ask = JOptionPane.showConfirmDialog(this, lbl1, "Cảnh Báo!", JOptionPane.YES_NO_OPTION);
			if(ask == JOptionPane.YES_OPTION) {
		    	loaiPhong_DAO.deleteLoaiPhong(txtMaLoaiP.getText());
		        DocDuLieuDatabaseVaoTable();
				xoaRongTextfields();
				JLabel lbl2 = new JLabel("Xóa thành công");
				lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl2);
				if(row < loaiPhong_DAO.getAllLoaiPhong().size() - 1) {
					selectedRow(row);
				} else if(loaiPhong_DAO.getAllLoaiPhong().size() > 0) {
					row = 0;
					selectedRow(row);
				}
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn loại phòng cần xóa");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed
    
    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
    	xoaRongTextfields();
    }//GEN-LAST:event_btnCapNhatActionPerformed

	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<LoaiPhong> list = loaiPhong_DAO.getAllLoaiPhong();
				for (LoaiPhong lp : list) {
					Object [] row = {lp.getMaLoai(),lp.getTenloai(),lp.getSoNguoiToiDa(),Math.round(lp.getGiaPhong())};
					model.addRow(row);
				}
	}
	private void xoaRongTextfields() {
		txtMaLoaiP.setText(loaiPhong_DAO.getMaLoaiP());
		txtTenLoaiP.setText("");
		txtSoNguoiToiDa.setText("");
		txtGiaP.setText("");
	}
	private void selectedRow(int row) {
		if(row != -1) {
			tblLoaiP.setRowSelectionInterval(row, row);
			tblLoaiP.scrollRectToVisible(tblLoaiP.getCellRect(row, row, true));
		}
	}
	private boolean validData() {
		String maLP = txtMaLoaiP.getText().trim(), gia = txtGiaP.getText().trim(), soNguoi = txtSoNguoiToiDa.getText().trim(); 

		if (!(maLP.length() > 0 && maLP.matches("LP\\d{3}"))) {
			JLabel lbl3 = new JLabel("Error: Mã loại phòng theo mẫu: LP + Dãy gồm 3 chữ số");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
			txtMaLoaiP.requestFocus();;
			return false;
		}
		if (gia.length() > 0) {
			try {
				double y = Double.parseDouble(gia);
				if (y <= 0) {
					JLabel lbl4 = new JLabel("Error: Giá phòng phải lớn hơn 0.");
					lbl4.setFont(new Font("Arial", Font.PLAIN, 18));
					JOptionPane.showMessageDialog(this, lbl4);
					txtGiaP.requestFocus();
					return false;
				}
			} catch (NumberFormatException e) {
				JLabel lbl5 = new JLabel("Error: Giá phòng phải nhập số.");
				lbl5.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl5);
				txtGiaP.requestFocus();
				return false;
			}
		}
		if (soNguoi.length() > 0) {
			try {
				int y = Integer.parseInt(soNguoi);
				if (y <= 0) {
					JLabel lbl4 = new JLabel("Error: Số người phải lớn hơn 0.");
					lbl4.setFont(new Font("Arial", Font.PLAIN, 18));
					JOptionPane.showMessageDialog(this, lbl4);
					txtSoNguoiToiDa.requestFocus();
					return false;
				}
			} catch (NumberFormatException e) {
				JLabel lbl5 = new JLabel("Error: Số người phải nhập số.");
				lbl5.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl5);
				txtSoNguoiToiDa.requestFocus();
				return false;
			}
		}
		return true;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel lblGiaP;
    private javax.swing.JLabel lblSoNguoiToiDa;
    private javax.swing.JLabel lblMaLoaiP;
    private javax.swing.JLabel lblTenLoaiP;
    private javax.swing.JPanel pnlDanhSachLoaiP;
    private javax.swing.JPanel pnlSuKien;
    private javax.swing.JPanel pnlThongTinLP;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tblLoaiP;
    private javax.swing.JTextField txtGiaP;
    private javax.swing.JTextField txtSoNguoiToiDa;
    private javax.swing.JTextField txtMaLoaiP;
    private javax.swing.JTextField txtTenLoaiP;
    // End of variables declaration//GEN-END:variables
}
