/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.DichVu_DAO;
import dao.LoaiDichVu_DAO;
import entity.DichVu;
import entity.LoaiDichVu;
import entity.NhanVien;

/**
 *
 * @author dell
 */
public class JPanel_TCDichVu extends javax.swing.JPanel {
	private DichVu_DAO dichVu_DAO;
	private LoaiDichVu_DAO loaiDV_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form Panel1
     */
    public JPanel_TCDichVu() {
        initComponents();
        tblDichVu.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblDichVu.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		dichVu_DAO = new DichVu_DAO();
		loaiDV_DAO = new LoaiDichVu_DAO();
		DocDuLieuDatabaseVaoTable();
        loadCBBLoaiDV(cboLoaiDV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinTC = new javax.swing.JPanel();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblDonViTinh = new javax.swing.JLabel();
        lblTrangThaiKD = new javax.swing.JLabel();
        dchHSD = new com.toedter.calendar.JDateChooser();
        txtGia = new javax.swing.JTextField();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblLoaiDV = new javax.swing.JLabel();
        cboLoaiDV = new javax.swing.JComboBox<>();
        lblGia = new javax.swing.JLabel();
        cboTrangThaiKD = new javax.swing.JComboBox<>();
        lblHanSuDung = new javax.swing.JLabel();
        txtDonViTinh = new javax.swing.JTextField();
        pnlSuKien = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnlDanhSachDV = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();

        pnlThongTinTC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Tra Cứu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlThongTinTC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMaDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaDV.setText("Mã Dịch Vụ:");

        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaDV.setMinimumSize(new java.awt.Dimension(50, 35));


        lblDonViTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDonViTinh.setText("Đơn Vị Tính:");

        lblTrangThaiKD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThaiKD.setText("Trạng Thái KD:");

        dchHSD.setDateFormatString("dd-MM-yyyy");
        dchHSD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dchHSD.setMinimumSize(new java.awt.Dimension(50, 33));

        txtGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGia.setMinimumSize(new java.awt.Dimension(50, 35));

        lblTenDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenDV.setText("Tên Dịch Vụ:");

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenDV.setMinimumSize(new java.awt.Dimension(50, 35));

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoLuong.setText("Số Lượng:");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoLuong.setMinimumSize(new java.awt.Dimension(50, 35));

        lblLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLoaiDV.setText("Loại Dịch Vụ:");

        cboLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cboLoaiDV.setMinimumSize(new java.awt.Dimension(50, 35));

        lblGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGia.setText("Giá:");

        cboTrangThaiKD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboTrangThaiKD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng Thái KD","Đang Kinh Doanh", "Ngưng Kinh Doanh" }));
        cboTrangThaiKD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboTrangThaiKD.setMinimumSize(new java.awt.Dimension(50, 35));

        lblHanSuDung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHanSuDung.setText("Hạn Sử Dụng:");

        txtDonViTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDonViTinh.setMinimumSize(new java.awt.Dimension(50, 35));


        javax.swing.GroupLayout pnlThongTinTCLayout = new javax.swing.GroupLayout(pnlThongTinTC);
        pnlThongTinTC.setLayout(pnlThongTinTCLayout);
        pnlThongTinTCLayout.setHorizontalGroup(
            pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTCLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDonViTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrangThaiKD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtDonViTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(cboTrangThaiKD, 0, 390, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoaiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoaiDV, 0, 390, Short.MAX_VALUE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtTenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHanSuDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dchHSD, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        pnlThongTinTCLayout.setVerticalGroup(
            pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinTCLayout.createSequentialGroup()
                        .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dchHSD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrangThaiKD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTrangThaiKD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon("icon/TC_icon.png")); // NOI18N
        btnTimKiem.setBackground(new Color(0,191,255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("icon/LamMoi_icon.png")); // NOI18N
        btnLamMoi.setBackground(new Color(0,191,255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuKienLayout = new javax.swing.GroupLayout(pnlSuKien);
        pnlSuKien.setLayout(pnlSuKienLayout);
        pnlSuKienLayout.setHorizontalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSuKienLayout.setVerticalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnlDanhSachDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Dịch Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlDanhSachDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá (VNĐ)", "Đơn Vị Tính", "Số Lượng", "Hạn Sử Dụng", "Trạng Thái KD", "Loại Dịch Vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDichVu.setRowHeight(30);
        tblDichVu.getTableHeader().setBackground(new Color(255, 127, 0));
        tblDichVu.setShowHorizontalLines(true);
        tblDichVu.setShowVerticalLines(true);
        scr.setViewportView(tblDichVu);

        javax.swing.GroupLayout pnlDanhSachDVLayout = new javax.swing.GroupLayout(pnlDanhSachDV);
        pnlDanhSachDV.setLayout(pnlDanhSachDVLayout);
        pnlDanhSachDVLayout.setHorizontalGroup(
            pnlDanhSachDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhSachDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE))
        );
        pnlDanhSachDVLayout.setVerticalGroup(
            pnlDanhSachDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(pnlDanhSachDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDanhSachDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinTC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDanhSachDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDVActionPerformed
		model.setRowCount(0);
		DocDuLieuDatabaseVaoTable();
		xoaRongTextfields();
    }//GEN-LAST:event_txtMaDVActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    	String tt,ngayHH;
    	if(cboTrangThaiKD.getSelectedItem().equals("Ngưng Kinh Doanh"))
    		tt = "0";
    	else if(cboTrangThaiKD.getSelectedIndex()==0)
    		tt = "";
    	else
    		tt = "1";
    	if(dchHSD.getDate()==null)
    		ngayHH = "";
    	else
    		ngayHH = (new SimpleDateFormat("yyyy-MM-dd")).format(dchHSD.getDate());
    	String maDV = txtMaDV.getText(), tenDV = txtTenDV.getText(),
    			gia = txtGia.getText(), donViTinh = txtDonViTinh.getText(), soLuong = txtSoLuong.getText(), loaiDV = cboLoaiDV.getSelectedItem().toString();
    	if(cboLoaiDV.getSelectedIndex()==0)
    		loaiDV = "";
    	model.setRowCount(0);
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		ArrayList<DichVu> dsDV = dichVu_DAO.getDichVu(maDV, tenDV, gia, donViTinh, soLuong, ngayHH, tt, loaiDV);
		for(DichVu dv : dsDV) {
			String trangThai = "Ngưng Kinh Doanh";
			if(dv.isTrangThaiKD()==true)
				trangThai="Đang Kinh Doanh";
			if(dv.getSoLuong()==-1) {
				Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),formatter.format(dv.getGia())
						,dv.getDonViTinh(),"","",trangThai,dv.getLoaiDichVu().getTenLoai()};
				model.addRow(row);
			}
			else {
				Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),formatter.format(dv.getGia())
						,dv.getDonViTinh(),dv.getSoLuong(),dv.getHanSuDung(),trangThai,dv.getLoaiDichVu().getTenLoai()};
				model.addRow(row);
			}
		}
    }//GEN-LAST:event_btnTimKiemActionPerformed

	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		List<DichVu> list = dichVu_DAO.getAllDichVu();
				for (DichVu dv : list) {	
					String tt = "Đang Kinh Doanh";
					if(dv.isTrangThaiKD()==false)
						tt="Ngưng Kinh Doanh";	
					if(dv.getSoLuong()==-1) {
						Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),formatter.format(dv.getGia())
								,dv.getDonViTinh(),"","",tt,dv.getLoaiDichVu().getTenLoai()};
						model.addRow(row);
					}
					else {
						Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),formatter.format(dv.getGia())
								,dv.getDonViTinh(),dv.getSoLuong(),dv.getHanSuDung(),tt,dv.getLoaiDichVu().getTenLoai()};
						model.addRow(row);
					}
				}
	}

	public void loadCBBLoaiDV(JComboBox<String> c) {
		c.removeAllItems();
		c.addItem("Loại Dịch Vụ");
		for (LoaiDichVu ldv : loaiDV_DAO.getAllLoaiDichVu()) {
			c.addItem(ldv.getTenLoai());
		}
	}
	private void xoaRongTextfields() {
        txtMaDV.setText("");
		txtTenDV.setText("");
		cboTrangThaiKD.setSelectedIndex(0);
		dchHSD.setDate(null);
		txtGia.setText("");
		txtDonViTinh.setText("");
		txtSoLuong.setText("");
		cboLoaiDV.setSelectedIndex(0);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboTrangThaiKD;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private com.toedter.calendar.JDateChooser dchHSD;
    private javax.swing.JLabel lblDonViTinh;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblHanSuDung;
    private javax.swing.JLabel lblLoaiDV;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTrangThaiKD;
    private javax.swing.JPanel pnlDanhSachDV;
    private javax.swing.JPanel pnlSuKien;
    private javax.swing.JPanel pnlThongTinTC;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenDV;
    // End of variables declaration//GEN-END:variables
}
