/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.NhanVien_DAO;
import dao.Phong_DAO;
import entity.HoaDon;
import entity.NhanVien;

/**
 *
 * @author dell
 */
public class JPanel_TCHoaDon extends javax.swing.JPanel {
	private Phong_DAO phong_DAO;
	private KhachHang_DAO khachHang_DAO;
	private NhanVien_DAO nhanVien_DAO;
	private HoaDon_DAO hoaDon_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form Panel1
     */
    public JPanel_TCHoaDon() {
        initComponents();
        tblHoaDon.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblHoaDon.getModel();
 		try {
 			Connect.getInstance().connect();
 		} catch (SQLException e1) {
 			// TODO Auto-generated catch block
 			e1.printStackTrace();
 		}
 		phong_DAO = new Phong_DAO();
 		hoaDon_DAO = new HoaDon_DAO();
 		khachHang_DAO = new KhachHang_DAO();
 		nhanVien_DAO = new NhanVien_DAO();
 		DocDuLieuDatabaseVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinTC = new javax.swing.JPanel();
        lblMaHD = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        lblTenKH = new javax.swing.JLabel();
        lblNgayLapHD = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        lblTenNV = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        dchNgayLapHD = new com.toedter.calendar.JDateChooser();
        cboTrangThai = new javax.swing.JComboBox<>();
        txtTenKH = new javax.swing.JTextField();
        pnlSuKien = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnlDanhSachHD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();

        pnlThongTinTC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Tra Cứu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlThongTinTC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMaHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaHD.setText("Mã HD:");

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaHD.setMinimumSize(new java.awt.Dimension(50, 35));


        lblTenKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenKH.setText("Tên KH:");

        lblNgayLapHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayLapHD.setText("Ngày Lập HD:");

        lblPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhong.setText("Phòng:");

        txtPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhong.setMinimumSize(new java.awt.Dimension(50, 35));

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenNV.setText("Tên NV:");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai.setText("Trạng Thái:");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNV.setMinimumSize(new java.awt.Dimension(50, 35));


        dchNgayLapHD.setDateFormatString("dd - MM - yyyy");
        dchNgayLapHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dchNgayLapHD.setMinimumSize(new java.awt.Dimension(50, 33));

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng Thái", "Đã Thanh Toán", "Chưa Thanh Toán" }));
        cboTrangThai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboTrangThai.setMinimumSize(new java.awt.Dimension(50, 35));

        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenKH.setMinimumSize(new java.awt.Dimension(50, 35));


        javax.swing.GroupLayout pnlThongTinTCLayout = new javax.swing.GroupLayout(pnlThongTinTC);
        pnlThongTinTC.setLayout(pnlThongTinTCLayout);
        pnlThongTinTCLayout.setHorizontalGroup(
            pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTCLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(dchNgayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrangThai, 0, 390, Short.MAX_VALUE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        pnlThongTinTCLayout.setVerticalGroup(
            pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTCLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dchNgayLapHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon("icon/TC_icon.png")); // NOI18N
        btnTimKiem.setBackground(new Color(0,191,255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("icon/LamMoi_icon.png")); // NOI18N
        btnLamMoi.setBackground(new Color(0,191,255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuKienLayout = new javax.swing.GroupLayout(pnlSuKien);
        pnlSuKien.setLayout(pnlSuKienLayout);
        pnlSuKienLayout.setHorizontalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSuKienLayout.setVerticalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnlDanhSachHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlDanhSachHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã HD", "Ngày Lập HD", "Nhân Viên", "Khách Hàng", "Phòng", "Giờ Vào", "Giờ Ra", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(30);
        tblHoaDon.getTableHeader().setBackground(new Color(255, 127, 0));
        tblHoaDon.setShowHorizontalLines(true);
        tblHoaDon.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout pnlDanhSachHDLayout = new javax.swing.GroupLayout(pnlDanhSachHD);
        pnlDanhSachHD.setLayout(pnlDanhSachHDLayout);
        pnlDanhSachHDLayout.setHorizontalGroup(
            pnlDanhSachHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhSachHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE))
        );
        pnlDanhSachHDLayout.setVerticalGroup(
            pnlDanhSachHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(pnlDanhSachHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDanhSachHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinTC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDanhSachHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
		model.setRowCount(0);
		DocDuLieuDatabaseVaoTable();
		xoaRongTextfields();
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    	String tt,ngayLapHD;
    	if(cboTrangThai.getSelectedItem().equals("Chưa Thanh Toán"))
    		tt = "0";
    	else if(cboTrangThai.getSelectedIndex()==0)
    		tt = "";
    	else
    		tt = "1";
    	if(dchNgayLapHD.getDate()==null)
    		ngayLapHD = "";
    	else
    		ngayLapHD = (new SimpleDateFormat("yyyy-MM-dd")).format(dchNgayLapHD.getDate());
    	String maHD = txtMaHD.getText(), tenNV = txtTenNV.getText(),
    			tenKH = txtTenKH.getText(), tenPhong = txtPhong.getText();
    	model.setRowCount(0);
		ArrayList<HoaDon> dsHD = hoaDon_DAO.getHoaDon(maHD, ngayLapHD, tenNV, tenKH, tenPhong, tt);
		for (HoaDon hd : dsHD) {	
			String trangThai = "Đã Thanh Toán";
			if(hd.isTrangThai()==false)
				trangThai="Chưa Thanh Toán";	
			Object [] row = {hd.getMaHoaDon(),hd.getNgayLapHD(),hd.getNhanvien().getTenNV(),hd.getKhachhang().getTenKhachHang(),hd.getPhong().getTenPhong(),hd.getGioVao(),hd.getGioRa(),trangThai};
			model.addRow(row);
		}
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<HoaDon> list = hoaDon_DAO.getAllHoaDon();
				for (HoaDon hd : list) {	
					String tt = "Đã Thanh Toán";
					if(hd.isTrangThai()==false)
						tt="Chưa Thanh Toán";	
					if(hd.getGioRa().toString().equals("00:00:59")) {
						Object [] row = {hd.getMaHoaDon(),hd.getNgayLapHD(),hd.getNhanvien().getTenNV(),hd.getKhachhang().getTenKhachHang(),hd.getPhong().getTenPhong(),hd.getGioVao(),"Chưa biết",tt};
						model.addRow(row);
					}
					else {
						Object [] row = {hd.getMaHoaDon(),hd.getNgayLapHD(),hd.getNhanvien().getTenNV(),hd.getKhachhang().getTenKhachHang(),hd.getPhong().getTenPhong(),hd.getGioVao(),hd.getGioRa(),tt};
						model.addRow(row);
					}
				}
	}
	
	private void xoaRongTextfields() {
		txtMaHD.setText("");
		txtTenNV.setText("");
		txtPhong.setText("");
		dchNgayLapHD.setDate(null);
		txtTenKH.setText("");
		cboTrangThai.setSelectedIndex(0);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboTrangThai;
    private com.toedter.calendar.JDateChooser dchNgayLapHD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblNgayLapHD;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlDanhSachHD;
    private javax.swing.JPanel pnlSuKien;
    private javax.swing.JPanel pnlThongTinTC;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
