/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.DichVu_DAO;
import dao.LoaiDichVu_DAO;
import entity.DichVu;

/**
 *
 * @author dell
 */
public class JPanel_TKDichVuSapHet extends javax.swing.JPanel {
	private DichVu_DAO dichVu_DAO;
	private LoaiDichVu_DAO loaiDV_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form JPanelTKDichVuSapHetHan
     */
    public JPanel_TKDichVuSapHet() {
        initComponents();
        tblDanhSachDVSapHet.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblDanhSachDVSapHet.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		dichVu_DAO = new DichVu_DAO();
		loaiDV_DAO = new LoaiDichVu_DAO();
		DocDuLieuDatabaseVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDichVuSapHet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachDVSapHet = new javax.swing.JTable();

        lblDichVuSapHet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDichVuSapHet.setText("Dịch Vụ Sắp Hết");

        tblDanhSachDVSapHet.setFont(new java.awt.Font("Segoe UI", 0, 18));
        tblDanhSachDVSapHet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                    "Mã DV", "Tên DV", "Giá (VNĐ)", "Đơn Vị Tính", "Số Lượng", "Hạn Sử Dụng", "Trạng Thái KD", "Loại Dịch Vụ"
            }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachDVSapHet.setRowHeight(30);
        tblDanhSachDVSapHet.getTableHeader().setBackground(new Color(255, 127, 0));
        tblDanhSachDVSapHet.setShowHorizontalLines(true);
        tblDanhSachDVSapHet.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblDanhSachDVSapHet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDichVuSapHet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDichVuSapHet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		List<DichVu> list = dichVu_DAO.getDichVuHetSL();
				for (DichVu dv : list) {	
					String tt = "Đang Kinh Doanh";
					if(dv.isTrangThaiKD()==false)
						tt="Ngưng Kinh Doanh";	
					if(dv.getSoLuong()!=-1) {
						Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),formatter.format(dv.getGia())
								,dv.getDonViTinh(),dv.getSoLuong(),dv.getHanSuDung(),tt,dv.getLoaiDichVu().getTenLoai()};
						model.addRow(row);
					}
				}
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDichVuSapHet;
    private javax.swing.JTable tblDanhSachDVSapHet;
    // End of variables declaration//GEN-END:variables
}
