/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.CT_HoaDon_DAO;
import dao.DichVu_DAO;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.LoaiDichVu_DAO;
import entity.CT_HoaDon;
import entity.DichVu;
import entity.HoaDon;
import entity.KhachHang;

/**
 *
 * @author dell
 */
public class JPanel_TKKhachHangTiemNang extends javax.swing.JPanel {
	private DefaultTableModel model;
	private HoaDon_DAO hoaDon_DAO;
	private CT_HoaDon_DAO ct_HoaDon_DAO;
	private KhachHang_DAO khachHang_DAO;

    /**
     * Creates new form JPanelTKDichVuSapHetHan
     */
    public JPanel_TKKhachHangTiemNang() {
        initComponents();
        tblDanhSachKHTN.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblDanhSachKHTN.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		khachHang_DAO = new KhachHang_DAO(); 
		hoaDon_DAO = new HoaDon_DAO();
		ct_HoaDon_DAO = new CT_HoaDon_DAO();
		DocDuLieuDatabaseVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKHTN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachKHTN = new javax.swing.JTable();
        lblCongthuc = new JLabel();

        lblKHTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKHTN.setText("KHÁCH HÀNG TIỀM NĂNG");
        
        lblCongthuc.setFont(new java.awt.Font("Segoe UI", 0, 20));
        lblCongthuc.setText("Quy ước tích điểm: Cứ 100.000đ = 1 điểm");
        lblCongthuc.setForeground(new Color(255,0,0));

        tblDanhSachKHTN.setFont(new java.awt.Font("Segoe UI", 0, 18));
        tblDanhSachKHTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách hàng","Số Điện Thoại", "Số Lần Đến", "Tổng Hóa Đơn (VNĐ)", "Tích Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachKHTN.setRowHeight(30);
        tblDanhSachKHTN.getTableHeader().setBackground(new Color(255, 127, 0));
        tblDanhSachKHTN.setShowHorizontalLines(true);
        tblDanhSachKHTN.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblDanhSachKHTN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCongthuc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKHTN)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1908, 2100))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblKHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, 1000)
                .addGap(20, 20, 20)
                .addComponent(lblCongthuc)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<KhachHang> list = khachHang_DAO.getKhachHangTiemNang();
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		for (KhachHang kh : list) {
			String s = String.valueOf(khachHang_DAO.getTongHoaDonTheoMa(kh.getMaKhachHang()) / 100000).split("\\.")[0]; 
			Object [] row = {kh.getMaKhachHang(),kh.getTenKhachHang(),kh.getSoDT(),khachHang_DAO.getSoLanDenTheoMa(kh.getMaKhachHang()), formatter.format(khachHang_DAO.getTongHoaDonTheoMa(kh.getMaKhachHang())),s};
			model.addRow(row);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKHTN;
    private javax.swing.JTable tblDanhSachKHTN;
    private JLabel lblCongthuc;
    // End of variables declaration//GEN-END:variables
}
