/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.ChucVu_DAO;
import entity.ChucVu;

/**
 *
 * @author dell
 */
public class JPanel_DMChucVu extends javax.swing.JPanel {
	private ChucVu_DAO chucVu_DAO;
	private DefaultTableModel model;

    /**
     * Creates new form Panel1
     */
    public JPanel_DMChucVu() {
        initComponents();
        tblChucVu.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblChucVu.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		chucVu_DAO = new ChucVu_DAO();
		DocDuLieuDatabaseVaoTable();
		txtMaCV.setText(chucVu_DAO.getMaCV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTinCV = new javax.swing.JPanel();
        lblMaCV = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        lblTenCV = new javax.swing.JLabel();
        txtTenCV = new javax.swing.JTextField();
        pnlSuKien = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        pnlDanhSachCV = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();

        pnlThongTinCV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Chức Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlThongTinCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMaCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaCV.setText("Mã Chức Vụ:");

        txtMaCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaCV.setMinimumSize(new java.awt.Dimension(50, 35));


        lblTenCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenCV.setText("Tên Chức Vụ:");

        txtTenCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenCV.setMinimumSize(new java.awt.Dimension(50, 35));

        javax.swing.GroupLayout pnlThongTinCVLayout = new javax.swing.GroupLayout(pnlThongTinCV);
        pnlThongTinCV.setLayout(pnlThongTinCVLayout);
        pnlThongTinCVLayout.setHorizontalGroup(
            pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinCVLayout.createSequentialGroup()
                .addContainerGap(498, Short.MAX_VALUE)
                .addGroup(pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaCV, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(lblTenCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenCV, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(txtMaCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(615, Short.MAX_VALUE))
        );
        pnlThongTinCVLayout.setVerticalGroup(
            pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinCVLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCapNhat.setBackground(new Color(0,191,255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon("icon/CN-icon.png")); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoa.setBackground(new Color(0,191,255));
        btnXoa.setIcon(new javax.swing.ImageIcon("icon/Xoa_icon.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnThem.setBackground(new Color(0,191,255));
        btnThem.setIcon(new javax.swing.ImageIcon("icon/Them_icon.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnXoaTrang.setBackground(new Color(0,191,255));
        btnXoaTrang.setIcon(new javax.swing.ImageIcon("icon/XT_icon.png")); // NOI18N
        btnXoaTrang.setText("Xóa Trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuKienLayout = new javax.swing.GroupLayout(pnlSuKien);
        pnlSuKien.setLayout(pnlSuKienLayout);
        pnlSuKienLayout.setHorizontalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        pnlSuKienLayout.setVerticalGroup(
            pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuKienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        pnlDanhSachCV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Chức Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlDanhSachCV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Chức Vụ", "Tên Chức Vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblChucVu.setRowHeight(30);
        tblChucVu.getTableHeader().setBackground(new Color(255, 127, 0));
        tblChucVu.setShowHorizontalLines(true);
        tblChucVu.setShowVerticalLines(true);
        scr.setViewportView(tblChucVu);

        javax.swing.GroupLayout pnlDanhSachCVLayout = new javax.swing.GroupLayout(pnlDanhSachCV);
        pnlDanhSachCV.setLayout(pnlDanhSachCVLayout);
        pnlDanhSachCVLayout.setHorizontalGroup(
            pnlDanhSachCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhSachCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1569, Short.MAX_VALUE))
        );
        pnlDanhSachCVLayout.setVerticalGroup(
            pnlDanhSachCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(pnlDanhSachCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDanhSachCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinCV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDanhSachCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
		tblChucVu.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				int row = tblChucVu.getSelectedRow();
				txtMaCV.setText(model.getValueAt(row, 0).toString());
				txtTenCV.setText(model.getValueAt(row, 1).toString());
			}
		});
    }// </editor-fold>//GEN-END:initComponents
    

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		if (txtMaCV.getText().equals("") || txtTenCV.getText().equals("")) {
			JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl1);
		} else {
	        if(validData()) {
	            ChucVu cv = new ChucVu(txtMaCV.getText(), txtTenCV.getText());
				if(chucVu_DAO.getAllChucVu().contains(cv)) {
					JLabel lbl2 = new JLabel("Không được thêm trùng mã chức vụ");
					lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
					JOptionPane.showMessageDialog(this, lbl2);
				} else {
		            chucVu_DAO.addChucVu(cv);
		            DocDuLieuDatabaseVaoTable();
		            xoaRongTextfields();
				}
	        }
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed

    
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblChucVu.getSelectedRow();
		if (row != -1) {
	    	if (txtMaCV.getText().equals("") || txtTenCV.getText().equals("")) {
				JLabel lbl1 = new JLabel("Vui lòng nhập đầy đủ thông tin!");
				lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl1);
			} else {
		        if(validData()) {
			        ChucVu cv = new ChucVu(txtMaCV.getText(), txtTenCV.getText());
			        chucVu_DAO.updateChucVu(cv);
			        DocDuLieuDatabaseVaoTable();
			        xoaRongTextfields();
		        }
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn chức vụ cần cập nhật");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
		int row = tblChucVu.getSelectedRow();
		if (row != -1) {
			JLabel lbl1 = new JLabel("Bạn có chắc muốn xóa không?");
			lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
			int ask = JOptionPane.showConfirmDialog(this, lbl1, "Cảnh Báo!", JOptionPane.YES_NO_OPTION);
			if(ask == JOptionPane.YES_OPTION) {
		    	chucVu_DAO.deleteChucVu(txtMaCV.getText());
		        DocDuLieuDatabaseVaoTable();
				xoaRongTextfields();
				JLabel lbl2 = new JLabel("Xóa thành công");
				lbl2.setFont(new Font("Arial", Font.PLAIN, 18));
				JOptionPane.showMessageDialog(this, lbl2);
				if(row < chucVu_DAO.getAllChucVu().size() - 1) {
					selectedRow(row);
				} else if(chucVu_DAO.getAllChucVu().size() > 0) {
					row = 0;
					selectedRow(row);
				}
			}
		}else {
			JLabel lbl3 = new JLabel("Bạn chưa chọn chức vụ cần xóa");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
		}
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCVActionPerformed
    	xoaRongTextfields();
    }//GEN-LAST:event_txtMaCVActionPerformed
    
	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<ChucVu> list = chucVu_DAO.getAllChucVu();
				for (ChucVu cv : list) {
					Object [] row = {cv.getMaChucVu(),cv.getTenChucVu()};
					model.addRow(row);
				}
	}
	private void xoaRongTextfields() {
		txtMaCV.setText(chucVu_DAO.getMaCV());
		txtTenCV.setText("");
	}
	private void selectedRow(int row) {
		if(row != -1) {
			tblChucVu.setRowSelectionInterval(row, row);
			tblChucVu.scrollRectToVisible(tblChucVu.getCellRect(row, row, true));
		}
	}
	private boolean validData() {
		String maCV = txtMaCV.getText().trim(); 

		if (!(maCV.length() > 0 && maCV.matches("CV\\d{3}"))) {
			JLabel lbl3 = new JLabel("Error: Mã chức vụ theo mẫu: CV + Dãy gồm 3 chữ số");
			lbl3.setFont(new Font("Arial", Font.PLAIN, 18));
			JOptionPane.showMessageDialog(this, lbl3);
			txtMaCV.requestFocus();;
			return false;
		}
		return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel lblMaCV;
    private javax.swing.JLabel lblTenCV;
    private javax.swing.JPanel pnlDanhSachCV;
    private javax.swing.JPanel pnlSuKien;
    private javax.swing.JPanel pnlThongTinCV;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtTenCV;
    // End of variables declaration//GEN-END:variables
}
