/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

import connect.Connect;
import dao.CT_HoaDon_DAO;
import dao.DichVu_DAO;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.LoaiDichVu_DAO;
import entity.CT_HoaDon;
import entity.DichVu;
import entity.HoaDon;
import entity.KhachHang;
import entity.LoaiPhong;

/**
 *
 * @author dell
 */
public class JPanel_TKDichVuUaThich extends javax.swing.JPanel {
	private DefaultTableModel model;
	private CT_HoaDon_DAO ct_HoaDon_DAO;
	private DichVu_DAO dichVu_DAO;

    /**
     * Creates new form JPanelTKDichVuSapHetHan
     */
    public JPanel_TKDichVuUaThich() {
        initComponents();
        tblDanhSachKHTN.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        model = (DefaultTableModel) tblDanhSachKHTN.getModel();
		try {
			Connect.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		dichVu_DAO = new DichVu_DAO();
		ct_HoaDon_DAO = new CT_HoaDon_DAO();
		DocDuLieuDatabaseVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKHTN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachKHTN = new javax.swing.JTable();
       

        lblKHTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKHTN.setText("DỊCH VỤ ƯA THÍCH");
        

        tblDanhSachKHTN.setFont(new java.awt.Font("Segoe UI", 0, 18));
        tblDanhSachKHTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ","Đơn Vị Tính", "Giá (VNĐ)", "Số Lượng Bán", "Tổng Doanh Thu (VNĐ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachKHTN.setRowHeight(30);
        tblDanhSachKHTN.getTableHeader().setBackground(new Color(255, 127, 0));
        tblDanhSachKHTN.setShowHorizontalLines(true);
        tblDanhSachKHTN.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblDanhSachKHTN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKHTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap()));
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblKHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
	public void DocDuLieuDatabaseVaoTable() {
		model.setRowCount(0);
		List<DichVu> list = dichVu_DAO.getDichVuUaThich();
		DecimalFormat formatter = new DecimalFormat("###,###,###");
		for (DichVu dv : list) {
			Object [] row = {dv.getMaDichVu(),dv.getTenDichVu(),dv.getDonViTinh(),formatter.format(dv.getGia()),dichVu_DAO.getSLBanTheoMa(dv.getMaDichVu()),formatter.format(dichVu_DAO.getTongDTTheoMa(dv.getMaDichVu()))};
			model.addRow(row);
		}
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKHTN;
    private javax.swing.JTable tblDanhSachKHTN;
    // End of variables declaration//GEN-END:variables
}
