package ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.data.category.DefaultCategoryDataset;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
//import com.itextpdf.text.List;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import dao.KhachHang_DAO;
import dao.HoaDon_DAO;
import dao.CT_HoaDon_DAO;
import entity.CT_HoaDon;
import entity.HoaDon;
import entity.KhachHang;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dell
 */
public class JPanel_BaoCao extends javax.swing.JPanel {

    
    /**
     * Creates new form JPaneBaoCao
     */
    public JPanel_BaoCao() {
        initComponents() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        btnBCDichVuHH = new javax.swing.JButton();
        btnBCDichVuHet = new javax.swing.JButton();
        btnBCDanhSachNV = new javax.swing.JButton();
        btnBCDanhSachHDCTT = new javax.swing.JButton();
        btnBCDanhSachPDP = new javax.swing.JButton();


        btnBCDichVuHH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBCDichVuHH.setBackground(new Color(0,191,255));
        btnBCDichVuHH.setText("Báo Cáo Danh Sách Dịch Vụ Sắp Hết Hạn");
        btnBCDichVuHH.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnBCDichVuHHActionPerformed(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (JRException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnBCDichVuHet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBCDichVuHet.setBackground(new Color(0,191,255));
        btnBCDichVuHet.setText("Báo Cáo Danh Sách Dịch Vụ Sắp Hết");
        btnBCDichVuHet.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
					btnBCDichVuHetActionPerformed(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (JRException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnBCDanhSachNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBCDanhSachNV.setBackground(new Color(0,191,255));
        btnBCDanhSachNV.setText("Báo Cáo Danh Sách Nhân Viên");
        btnBCDanhSachNV.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		try {
					btnBCDanhSachNhanVienActionPerformed(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (JRException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        });
        btnBCDanhSachHDCTT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBCDanhSachHDCTT.setBackground(new Color(0,191,255));
        btnBCDanhSachHDCTT.setText("Báo Cáo Danh Sách Hóa Đơn Chưa Thanh Toán");
        btnBCDanhSachHDCTT.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		try {
					btnBCDanhSachHDCTTActionPerformed(evt);
				} catch (FileNotFoundException | SQLException | JRException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        });
        btnBCDanhSachPDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBCDanhSachPDP.setBackground(new Color(0,191,255));
        btnBCDanhSachPDP.setText("Báo Cáo Danh Sách Phiếu Đặt Phòng");
        btnBCDanhSachPDP.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		try {
					btnBCDanhSachPDPActionPerformed(evt);
				} catch (FileNotFoundException | SQLException | JRException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBCDanhSachPDP, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBCDanhSachHDCTT, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBCDanhSachNV, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBCDichVuHet, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBCDichVuHH, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGap(47, 47, 47)
                .addComponent(btnBCDichVuHH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBCDichVuHet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBCDanhSachNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBCDanhSachHDCTT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBCDanhSachPDP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  private void btnBCDichVuHHActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, FileNotFoundException, JRException {//GEN-FIRST:event_btnBCDichVuHHActionPerformed
        // TODO add your handling code here:
    	
    	
   	 	Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLKaraoke","sa","sapassword");
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("CollectionBeanParam", con);
        InputStream input = new FileInputStream(new File("exportFile/baoCao/DVSapHetHan.jrxml"));                    
        JasperDesign jasperDesign = JRXmlLoader.load(input);
        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, con);
        JasperViewer.viewReport(jasperPrint, false);
        
    }//GEN-LAST:event_btnBCDichVuHHActionPerformed

    private void btnBCDichVuHetActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, FileNotFoundException, JRException {//GEN-FIRST:event_btnBCDichVuHetActionPerformed
        // TODO add your handling code here:
    	
    	 Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLKaraoke","sa","sapassword");
         Map<String, Object> parameters = new HashMap<String, Object>();
         parameters.put("CollectionBeanParam", con);
         InputStream input = new FileInputStream(new File("exportFile/baoCao/DVSapHet.jrxml"));                    
         JasperDesign jasperDesign = JRXmlLoader.load(input);
         JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
         JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, con);
         JasperViewer.viewReport(jasperPrint, false);
         
 	}
    //GEN-LAST:event_btnBCDichVuHetActionPerformed
    private void btnBCDanhSachNhanVienActionPerformed(ActionEvent evt) throws SQLException, FileNotFoundException, JRException {
		// TODO Auto-generated method stub
    	
   	 	Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLKaraoke","sa","sapassword");
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("CollectionBeanParam", con);
        InputStream input = new FileInputStream(new File("exportFile/baoCao/DSNhanVien.jrxml"));                    
        JasperDesign jasperDesign = JRXmlLoader.load(input);
        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, con);
        JasperViewer.viewReport(jasperPrint, false);
        
	}
    private void btnBCDanhSachHDCTTActionPerformed(ActionEvent evt) throws SQLException, FileNotFoundException, JRException {
		// TODO Auto-generated method stub
    	
   	 	Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLKaraoke","sa","sapassword");
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("CollectionBeanParam", con);
        InputStream input = new FileInputStream(new File("exportFile/baoCao/DSHDCTT.jrxml"));                    
        JasperDesign jasperDesign = JRXmlLoader.load(input);
        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, con);
        JasperViewer.viewReport(jasperPrint, false);
        
	}
    private void btnBCDanhSachPDPActionPerformed(ActionEvent evt) throws SQLException, FileNotFoundException, JRException {
		// TODO Auto-generated method stub
    	
	 	Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=QLKaraoke","sa","sapassword");
	    Map<String, Object> parameters = new HashMap<String, Object>();
	    parameters.put("CollectionBeanParam", con);
	    InputStream input = new FileInputStream(new File("exportFile/baoCao/DSPDP.jrxml"));                    
	    JasperDesign jasperDesign = JRXmlLoader.load(input);
	    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
	    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, con);
	    JasperViewer.viewReport(jasperPrint, false);
	    
		
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBCDanhSachHDCTT;
    private javax.swing.JButton btnBCDanhSachNV;
    private javax.swing.JButton btnBCDanhSachPDP;
    private javax.swing.JButton btnBCDichVuHH;
    private javax.swing.JButton btnBCDichVuHet;
    // End of variables declaration//GEN-END:variables
}
