/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.CT_HoaDon_DAO;
import dao.HoaDon_DAO;
import entity.CT_HoaDon;
import entity.HoaDon;
import entity.NhanVien;

/**
 *
 * @author dell
 */
public class JPanel_TKDTTheoNgayNV extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTKDTTheoNgay
     */
    public JPanel_TKDTTheoNgayNV() {
    	hoaDon_DAO = new HoaDon_DAO();
    	ct_HoaDon_DAO = new CT_HoaDon_DAO();
        initComponents();
        model = (DefaultTableModel) tblDanhSachHD.getModel();
        tblDanhSachHD.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNgay = new javax.swing.JLabel();
        dchNgayTK = new com.toedter.calendar.JDateChooser();
        lblTongHD = new javax.swing.JLabel();
        lblTongHD2 = new javax.swing.JLabel();
        lblTongDT = new javax.swing.JLabel();
        lblTongDT2 = new javax.swing.JLabel();
        scr = new javax.swing.JScrollPane();
        tblDanhSachHD = new javax.swing.JTable();
        btnThongKe = new JButton();

        lblNgay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgay.setText("Thống Kê Doanh Thu Theo Ngày: ");

        dchNgayTK.setDateFormatString("dd - MM - yyyy");
        dchNgayTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18));
        btnThongKe.setIcon(new javax.swing.ImageIcon("icon/TK_icon.png"));
        btnThongKe.setBackground(new Color(230, 125, 0));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        lblTongHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongHD.setText("Tổng Hóa Đơn:");

        lblTongHD2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongDT.setText("Tổng Doanh Thu Trong Ngày:");

        lblTongDT2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblDanhSachHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblDanhSachHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã HD", "Khách Hàng", "Phòng", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachHD.setRowHeight(30);
        tblDanhSachHD.getTableHeader().setBackground(new Color(255, 127, 0));
        tblDanhSachHD.setShowHorizontalLines(true);
        tblDanhSachHD.setShowVerticalLines(true);
        scr.setViewportView(tblDanhSachHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scr)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTongHD2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblTongDT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTongDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNgay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dchNgayTK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        		.addComponent(btnThongKe,javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(dchNgayTK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                	.addComponent(btnThongKe,javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTongHD2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTongDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongDT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
    }
    
   
    private void btnThongKeActionPerformed(ActionEvent evt) {
    	
    	modelNV = (DefaultTableModel) JPanel_TKDoanhThu.getTable().getModel();
    	int row =JPanel_TKDoanhThu.getTable().getSelectedRow();
    	if(row<0) {
    		JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên bạn muốn thống kê");
    	}else {
    		String maNV = modelNV.getValueAt(row, 0).toString();
    	
    		if(dchNgayTK.getDate()==null) {
    			JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày bạn muốn thống kê");
    		}else {
    			model.setRowCount(0);
    			java.util.Date datetime = dchNgayTK.getDate();
    			java.sql.Date ngay = new java.sql.Date(datetime.getTime());
    			ArrayList<HoaDon> dsHD = hoaDon_DAO.getHDTheoNgayvaNV(ngay, maNV);
    			int i = 0;
    			double tongDT=0;
    			DecimalFormat formatter = new DecimalFormat("###,###,###");
    			for(HoaDon hd : dsHD) {
    				List<CT_HoaDon> dsCTHD = ct_HoaDon_DAO.getAllCTHDTheoMa(hd.getMaHoaDon());
        			if(dsCTHD==null) {
        				model.addRow(new Object[] { 
        						hd.getMaHoaDon(), hd.getKhachhang().getTenKhachHang(), hd.getPhong().getTenPhong(), formatter.format(hd.getTienPhong())
        						});
        				i++;
        				tongDT = tongDT + hd.getTienPhong();
        			}else {
            			double tongtien =0;
                		double tienDV = 0;
        				for(CT_HoaDon cthd : dsCTHD) {
        					tienDV = cthd.getSoLuong()*cthd.getGiaBan() + tienDV;
        				}
        				tongtien =tienDV + hd.getTienPhong();
        				model.addRow(new Object[] { 
        						hd.getMaHoaDon(), hd.getKhachhang().getTenKhachHang(), hd.getPhong().getTenPhong(), formatter.format(tongtien)
        						});
        				i++;
        				tongDT = tongDT + tongtien;
        			}
    			}
    			String thd = String.valueOf(i);
    			lblTongHD2.setText(thd);
    			lblTongDT2.setText(formatter.format(tongDT)+" VNĐ");
    		}
    	}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dchNgayTK;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTongDT;
    private javax.swing.JLabel lblTongDT2;
    private javax.swing.JLabel lblTongHD;
    private javax.swing.JLabel lblTongHD2;
    private JButton btnThongKe;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tblDanhSachHD;
    private DefaultTableModel model;
    private DefaultTableModel modelNV;
    private HoaDon_DAO hoaDon_DAO;
    private CT_HoaDon_DAO ct_HoaDon_DAO;
    // End of variables declaration//GEN-END:variables
}
